[general]

working_directory = "Dev"

[window]

opacity = 0.9
blur = true

[font]

normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[colors]

vi_mode_cursor = { text = '#000000', cursor = '#d3cdc3' }
cursor = { text = '#000000', cursor = '#d3cdc3' }
